CREATE TEXT TABLE Customers (ID INT GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) NOT NULL, FIRST VARCHAR(255), LAST VARCHAR(255))
CREATE TEXT TABLE Customers (ID INTEGER IDENTITY, FIRST VARCHAR(255), LAST VARCHAR(255))


SELECT lang, ou, ags, fcstGrp, StaffGrp, HndlMthd, fcstGrpId, week, SUM(val) AS val FROM dbo.1aFollowUpRatesInput where fcstGrpId ='CA-CA - NonAGS - ADV - FollowUp' GROUP BY lang, ou, ags, fcstGrp, StaffGrp, HndlMthd, fcstGrpId, week;

SELECT lang, ou, ags, fcstGrp, week, SUM(val) AS val FROM dbo.1aRawVolFcstInput GROUP BY lang, ou, ags, fcstGrp, week;

SELECT FR.lang, FR.ou, FR.ags, FR.fcstGrp, FR.fcstGrpId, FR.week, SUM(FR.val)*SUM(RVF.val) AS val FROM dbo.1aFollowUpRatesInput FR, dbo.1aRawVolFcstInput RVF
WHERE FR.lang = RVF.lang AND FR.ou = RVF.ou AND FR.ags = RVF.ags AND FR.fcstGrp = RVF.fcstGrp AND FR.week = RVF.week GROUP BY FR.lang, FR.ou, FR.ags, FR.fcstGrp, FR.StaffGrp, FR.HndlMthd, FR.fcstGrpId, FR.week;

SELECT R.lang FROM
 (SELECT lang, ou, ags, fcstGrp, StaffGrp, HndlMthd, fcstGrpId, week, SUM(val) AS val FROM dbo.1aFollowUpRatesInput GROUP BY lang, ou, ags, fcstGrp, StaffGrp, HndlMthd, fcstGrpId, week) AS R;

-- SELECT FR.lang, FR.ou, FR.ags, FR.fcstGrp, FR.fcstGrpId, FR.week, SUM(FR.val)*SUM(RVF.val) AS val
SELECT FR.*, RVF.*
FROM
(
SELECT lang, ou, ags, fcstGrp, StaffGrp, HndlMthd, fcstGrpId, week, SUM(val) AS val FROM dbo.1aFollowUpRatesInput GROUP BY lang, ou, ags, fcstGrp, StaffGrp, HndlMthd, fcstGrpId, week
) AS FR
INNER JOIN
(
SELECT lang, ou, ags, fcstGrp, week, SUM(val) AS val FROM dbo.1aRawVolFcstInput GROUP BY lang, ou, ags, fcstGrp, week
) AS RVF
WHERE FR.lang = RVF.lang AND FR.ou = RVF.ou AND FR.ags = RVF.ags AND FR.fcstGrp = RVF.fcstGrp AND FR.week = RVF.week;
